module.exports = {
    entry:'./client.js',
    mode:'development',
    output:{
        path:__dirname+'/deploy',
        filename:'app.js'
    },
    watch:true,
    module:{
        rules:[
            {
                test:/\.js$/,
                exclude:/node_modules/,
                use:[{
                    loader:'babel-loader'
                }]
            }
        ]
    }
};